# Conditions

In [1]:
import numpy as np

In [5]:
arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [8]:
#Se puede crar una variable con es condición
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
#Al usar la variable en el slice, se obtiene los índices tal cual la conidición
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [10]:
#También se puede hacer sólo con la condición
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
#Se puede usar la conjunción & 
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [12]:
#Se puede modificar las condiciones 
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)