# Operaciones

In [1]:
import numpy as np

In [3]:
lista = [1,2]
lista

[1, 2]

In [5]:
#Cuando le pedimos a python modificar una lista, lo que nos devuelve será una duplicación de esta y no el producto de los datos de la lista
lista * 2

[1, 2, 1, 2]

In [13]:
#Hacemos dos arreglos
arr = np.arange(0, 10)
arr2 = arr.copy()

#### Multiplicación

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Suma

In [10]:
arr + 2 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### División

In [14]:
#Aunque se de un error, la operación va a continuar
1 / arr

/tmp/ipykernel_737/627608811.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

#### Potencia

In [15]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Operaciones con arreglos

In [18]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Operaciones con matrices


In [20]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [21]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
#Las matrices funcionan con la misma posición indexada
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [23]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [24]:
matriz - matriz2


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### Producto punto

In [26]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [25]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [27]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])