<h1>Array<h1>

In [43]:
import numpy as np 

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arr = np.array(lista)

In [5]:
type(arr)

numpy.ndarray

<h2>Matriz<h2>

In [44]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h2>Slices<h2>

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[0]

1

In [10]:
arr[2]

3

In [11]:
arr[1] + arr[5]

8

In [12]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matriz[0]

array([1, 2, 3])

In [20]:
matriz[0,2]

3

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[0:3]

array([1, 2, 3])

In [32]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [33]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [34]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[::2]

array([1, 3, 5, 7, 9])

In [37]:
arr[::3]

array([1, 4, 7])

In [38]:
arr[-1]

9

In [39]:
arr[-3:]

array([7, 8, 9])

In [40]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])