<h1>Matriz en 3D<h1>

In [6]:
import numpy as np

In [7]:
Matriz3D = [[[1,2],[3,4]],[[5,6],[7,8]]]
Matriz3D = np.array(Matriz3D)
Matriz3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
Matriz3D[0]

array([[1, 2],
       [3, 4]])

In [9]:
Matriz3D[0,0]

array([1, 2])

In [11]:
Matriz3D[0:,1]

array([[3, 4],
       [7, 8]])

In [12]:
Matriz3D[0,1]


array([3, 4])

In [20]:
Matriz3D[0:,0:,1:]

array([[[2],
        [4]],

       [[6],
        [8]]])

In [21]:
Matriz3D[0:,0:,-1]

array([[2, 4],
       [6, 8]])