In [1]:
import numpy  as np

In [2]:
Tensor = np.array([1,2,3,4,5,6],ndmin=5)
print(Tensor)
Tensor.ndim

[[[[[1 2 3 4 5 6]]]]]


5

In [3]:
Tensor_6 = np.expand_dims(np.array(Tensor), axis=2)
print(Tensor_6)
Tensor_6.ndim

[[[[[[1 2 3 4 5 6]]]]]]


6

In [6]:
Tensor_1 = np.squeeze(Tensor_6)
print(Tensor_1, Tensor_1.ndim)

[1 2 3 4 5 6] 1
