### Creando Arrays

In [1]:
import numpy as np

In [2]:
#Creando una lista con range
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
#Crear un array desde 0 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Creando arrary con slice
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
#zeros se usa para crear un esquema previo
np.zeros(3)

array([0., 0., 0.])

In [7]:
#Ejemplo de matriz
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
#Este es parecido a zeros, pero los reemplaza por 1, y es con el mismo propósito
np.ones((10,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#Toma valores de un intervalo (Valor de inicio, valor final, n valores) - Distribución ordenada
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [11]:
#Crea una matriz con una diagonal - Álgebra lineal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#Genera valores aleatorios
np.random.rand()

0.6336527791106069

In [13]:
#Genera valores de una dimensión - Vector
np.random.rand(4)

array([0.14379329, 0.55761718, 0.91348499, 0.34943254])

In [14]:
#Si le agregamos un número, generará una matriz
np.random.rand(4,4)

array([[0.45019229, 0.96106863, 0.42437287, 0.16454673],
       [0.69898726, 0.33731419, 0.21512768, 0.17165667],
       [0.13197956, 0.28217548, 0.44654795, 0.26626038],
       [0.92843252, 0.03113166, 0.19252721, 0.18435739]])

In [15]:
#No hace arrays; trae valores enteros
np.random.randint(1,15)

5

In [16]:
#Se puede crear una estructura dentro (10,10)
np.random.randint(1,100,(10,10))

array([[66, 32, 56,  8, 37, 88, 40, 27, 77, 69],
       [92, 85, 40, 94, 73, 31,  2, 20, 88, 22],
       [72, 69, 12,  3, 51, 27, 43, 33, 79, 90],
       [68,  8, 48, 35,  1, 64,  2,  5, 99, 10],
       [67, 33, 85, 92, 91,  4, 78, 94, 23, 55],
       [54, 47, 94,  2, 12, 92, 21, 94, 91, 73],
       [39, 70, 84, 27, 95, 66, 14, 68, 89, 16],
       [18, 87, 75, 48, 76, 70, 61, 26, 30, 87],
       [56, 21, 96, 25, 73, 18, 62, 64, 94, 16],
       [94, 91, 10, 62, 18, 11, 50, 98, 82, 48]])