# Shape y Reshape

In [1]:
import numpy as np

In [6]:
arr = np.random.randint(1,10,(3,2))

## Shape

In [7]:
# Shape nos dice cuántas filas y columnas tiene un arreglo
arr.shape

(3, 2)

In [8]:
arr

array([[4, 8],
       [9, 8],
       [8, 3]])

## Reshape

In [9]:
# Reshape reordena los valores de la matriz, cambiando las filas y columnas
arr.reshape(1,6)

array([[4, 8, 9, 8, 8, 3]])

In [10]:
arr.reshape(2,3)

array([[4, 8, 9],
       [8, 8, 3]])

In [11]:
# Otra forma de usar reshape
np.reshape(arr, (1,6))

array([[4, 8, 9, 8, 8, 3]])

In [12]:
arr

array([[4, 8],
       [9, 8],
       [8, 3]])

In [14]:
# Esta es la forma en que hace C (C)
np.reshape(arr, (2,3),'C')

array([[4, 8, 9],
       [8, 8, 3]])

In [15]:
# Como lo hace Fortran (F)
np.reshape(arr, (2,3),'F')

array([[4, 8, 8],
       [9, 8, 3]])

In [16]:
# Como lo hace la forma de guardado del sistema propio (A)
np.reshape(arr, (2,3),'A')

array([[4, 8, 9],
       [8, 8, 3]])