# Funciones Principales de Numpy

In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,20,10)
arr

array([12, 19, 14,  8,  1, 15, 17, 17, 10, 17])

In [6]:
matriz = arr.reshape(2,5)
matriz

array([[12, 19, 14,  8,  1],
       [15, 17, 17, 10, 17]])

### Función Max

In [7]:
arr

array([12, 19, 14,  8,  1, 15, 17, 17, 10, 17])

In [9]:
#Retorna el número más grande
arr.max()

19

In [10]:
#Lo mismo en la matriz
matriz.max()

19

In [11]:
matriz

array([[12, 19, 14,  8,  1],
       [15, 17, 17, 10, 17]])

In [13]:
#Se puede hacer en diferentes ejes
matriz.max(1)

array([19, 17])

In [14]:
matriz.max(0)

array([15, 19, 17, 10, 17])

### Argmax

In [16]:
#Da como resultado el índice con el número más grande
arr.argmax()

1

In [17]:
matriz.argmax(0)

array([1, 0, 1, 1, 1])

### Min

In [26]:
arr

array([12, 19, 14,  8,  1, 15, 17, 17, 10, 17])

In [27]:
matriz

array([[12, 19, 14,  8,  1],
       [15, 17, 17, 10, 17]])

In [18]:
#Devuelve el valor más pequeño
arr.min()

1

In [19]:
matriz.min(0)

array([12, 17, 14,  8,  1])

### Argmin

In [23]:
### Argamin es lo contrario de argmax
arr.argmin()

4

In [25]:
matriz.argmin(1)

array([4, 3])

### ptp (pick to pick)

In [28]:
#Da la diferencia entra el valor más pequeño y el más grande (Para analizar datos)
arr.ptp()

18

In [29]:
matriz.ptp(0)

array([ 3,  2,  3,  2, 16])

### Percentil

In [35]:
### sort ordena de menor a mayor
arr.sort()
arr

array([ 1,  8, 10, 12, 14, 15, 17, 17, 17, 19])

In [33]:
### En este caso, da el valor que está a la mitad
np.percentile(arr,50)

14.5

### Mediana

In [36]:
#Entrega la mediana
np.median(arr)

14.5

In [37]:
np.median(matriz,0)

array([ 8. , 12.5, 13.5, 14.5, 16.5])

In [38]:
np.median(matriz,1)

array([10., 17.])

### STD (Desviación estándar)

In [39]:
np.std(arr)

5.176871642217914

In [41]:
#Desviación estándar elevada al cuadrado es igual a Varianza
np.std(arr) ** 2

26.8

### Varianza (var)

In [40]:
np.var(arr)

26.8

### Media (función mean)

In [42]:
np.mean(arr)

13.0

### Concatenar

In [52]:
a = np.array([[1,2],[3,4]])
b = np.array([4,6])

In [53]:
# b no tiene las mismas dimensiones que a, da error
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [46]:
a.ndim
b.ndim

1

In [55]:
#Se debe cambiar el número de dimensiones de b
b = np.expand_dims(b, axis=0)

In [56]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])

In [57]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [58]:
#La "T" significa transponer
np.concatenate((a,b.T), axis=1)

array([[1, 2, 4],
       [3, 4, 6]])