# Copy

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
trozo_de_arr = arr[0:6]

In [5]:
#Esta nueva variable seguirá haciendo modificaciones en el original
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [6]:
#Aquí se hace la modificación
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [7]:
#Afecta a la variable padre
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [16]:
#Se hace la copia del original
arr_copy = arr.copy()

In [17]:

arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [18]:
#Se vuelve a rellenar la lista para revisar que los cambios no afectan a la variable padre
arr_copy[:] = 100

In [13]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])